### PR TITLE
fix note representation time step overflow

### PR DESCRIPTION
**Pull request by TwinMooon**

### CODE REVIEW

**Comment by salu133445** [comment]
Hi, thanks for the pull request. The commits for fixing the overflow issue look fine to me. However, in my view, tempo is a global properties rather than an attribute of a note. `Note(time=0, duration=1, pitch=60, velocity=64, tempo=120)` does not make much sense to me. Some issues might arise if there are concurrent notes with different tempos or the notes are not sorted by time. Let me know if there are some specific use cases for doing this.

**Comment by salu133445** [comment]
The overflow bug has been fixed in 0f92edd (see #8).

**Comment by salu133445** [comment]
@TwinMooon Is there any specific use case for adding tempo to the note representation?

**Comment by TwinMooon** [comment]
@salu133445 Cool! I use the tempo feature in the music classification. But  using tempo in note presentation may suffer from contradiction in the music generation.

**Comment by salu133445** [comment]
@TwinMooon I see. It does have some potential use case for monophonic music. Could you open a separate pull request for the optional tempo encoding? Thank you.

**Comment by salu133445** [comment]
There might also be some potential use case in modeling expressive monophonic music. For example, with the tempo encoding, we can keep the note onsets and durations in metrical timing, while modeling the performance with varying tempo across time.

**Pull request closed without merging**
